baseURL = 'https://www.blog.aidanmaurinjones.com/'
languageCode = 'en-us'
title = 'Aidan Maurin-Jones'
theme = 'mainroad'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50

  [[menu.main]]
    name = "Newsletter Archive"
    url = "/newsletter/"
    weight = 60


[params]
  dateFormat = "January 2, 2006"   # keep (harmless)
  dateformat = "January 2, 2006"   # <- Mainroad usually reads this one
  post_meta = ["date"]
  description = "Aidan Maurin-Jones shares tools, automations, and thoughts on whatever’s interesting this week."
  rssFullText = true

  # (optional) keep your sidebar + widgets here under [params], not [Params]
  [params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "taglist", "clearall"]

  [params.widgets]
    tags_counter = true


# Use Google as the target (Mainroad’s default)
[params.widgets.search]
  url = "https://google.com/search"

  # Mainroad builds the full query for you. Leave these as docs recommend:
  [params.widgets.search.input]
    name = "sitesearch"
    pre  = ""
    
# These belong at top-level (you already have them right)
mainSections = ["posts"]
paginate = 10

rssURI = "index.xml"

[outputs]
home    = ["HTML"]   # keep only the global feed
section = ["HTML", "RSS"]          # no section feeds
taxonomy = ["HTML"]         # no tag/category feeds
term     = ["HTML"]

