baseURL = 'https://www.blog.aidanmaurinjones.com/'
languageCode = 'en-us'
title = 'Aidan Maurin-Jones'
theme = 'amj'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50

  [[menu.main]]
    name = "Newsletter Archive"
    url = "/newsletter/"
    weight = 60

[params]
  author = "Aidan Maurin-Jones"
  description = "Aidan Maurin-Jones shares tools, automations, and thoughts on whatever’s interesting this week."
  rssFullText = true
  mainSections = ["posts"]
  feedSections = ["posts", "newsletter"]

[pagination]
  pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
